import { Metadata } from "next";
import "./globals.css";
import { ErrorWrapper } from "./error-wrapper";

export const metadata: Metadata = {
  title: {
    default: "Next.js Tutorial - Codevolution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-400 p-4">
          <p>Header</p>
        </header>
        <ErrorWrapper>{children}</ErrorWrapper>
        <footer className="bg-gray-400 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
